name: Build and test Python package

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: whoan/docker-build-with-cache-action@v2
      with:
        username: "${{ secrets.DOCKER_USERNAME }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: "${{ secrets.DOCKER_USERNAME }}/sagemath-conda-coinor"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: sagecoin
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
    - name: Test package
      shell: bash -l {0}
      run: |
        sage --version
        python3 setup.py test
  build_with_ubuntu_sage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install SageMath and CBC
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install sagemath coinor-cbc coinor-libcbc-dev python-pkgconfig python-setuptools python-sphinx cython
    - name: Test package
      run: |
        sage --version
        sage setup.py test
