name: Build and test Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        activate-environment: sagecoin
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
    - name: Test package
      shell: bash -l {0}
      run: |
        sage --version
        python3 setup.py test
  build_with_ubuntu_sage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install SageMath and CBC
      run: |
        sudo apt install sagemath coinor-cbc
    - name: Test package
      run: |
        sage --version
        python3 setup.py test

